-- 코드를 입력하세요
SELECT S.USER_ID, S.PRODUCT_ID FROM ONLINE_SALE O
INNER JOIN ONLINE_SALE S ON O.USER_ID = S.USER_ID AND S.PRODUCT_ID = O.PRODUCT_ID
GROUP BY S.USER_ID, S.PRODUCT_ID HAVING COUNT(*) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

# SELECT * FROM ONLINE_SALE