-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE SUBSTR(SEX_UPON_INTAKE, 1, 6) = 'intact' AND SUBSTR(SEX_UPON_OUTCOME, 1, 6) != 'intact'
ORDER BY I.ANIMAL_ID;