SELECT YEAR(SALES_DATE) AS 'YEAR', MONTH(SALES_DATE) AS 'MONTH', COUNT(DISTINCT(O.USER_ID)) AS 'PURCHASED_USERS', ROUND(COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS 'PUCHASED_RATIO'
FROM
(SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = 2021) AS ta -- 2021년에 가입한 사람들
LEFT OUTER JOIN ONLINE_SALE O ON ta.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH
HAVING PURCHASED_USERS > 0
ORDER BY YEAR, MONTH;

-- SELECT * FROM ONLINE_SALE;

-- SELECT COUNT(DISTINCT(USER_ID)) FROM ONLINE_SALE WHERE MONTH(SALES_DATE) = 1;