-- 코드를 입력하세요
SELECT APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A JOIN PATIENT P
ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON D.DR_ID = MDDR_ID
WHERE SUBSTR(APNT_YMD, 1, 10) = '2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;