SELECT CONCAT ('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS'FILE_PATH'
FROM
(SELECT *
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC LIMIT 1) AS T -- 조회수 1위 게시물 조회
INNER JOIN USED_GOODS_FILE F ON T.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC;